name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run : docker build . -t flaubert1/redux-github-actions
    - run : echo "bf7a008d-c383-41d6-b4b2-ff1c0e535b07" | docker login -u flaubert1 --password-stdin
    - run : docker login -u flaubert1
    - run : docker push flaubert1/redux-github-actions